### PR TITLE
Use the border color for the vertical border.

### PR DESCRIPTION
**Pull request by Stebalien**
It seemed kind of silly to be using two different colors.

### CODE REVIEW

**Comment by nashamri** [comment]
It sure is silly :smile: thanks for this PR @Stebalien.

**Comment by codesuki** [comment]
Just my opinion but it looked way better before.

**Comment by jwintz** [comment]
I second. Moreover there is no way to get the previous color with spacemacs-theme-custom-colors.

- ju

**Comment by jwintz** [comment]
For the record, for those who want to revert the previous `vertical-border` color or set it to an arbitrary value without messing up with `spacemacs-common.el` here's a snippet:

```lisp
(custom-theme-set-faces 'spacemacs-dark `(vertical-border ((t (:foreground "#000000"))))
```

screen shot 2017-03-30 at 12 37 01

**Pull request merged**
