### PR TITLE
Change mu4e-modeline-face from func to yellow

### PR DESCRIPTION
**Pull request by jabranham**
Currently in an active buffer, it's pink/purple on top of a slightly
different pink/purple, which isn't great looking. This changes it to
yellow, which looks better.

### CODE REVIEW

**Comment by nashamri** [comment]
Hello @jabranham thanks for this :+1: 
I don't have `mu4e` installed and configured at the moment. Can you, please, attach a screenshot of this?
Much appreciated.

**Comment by jabranham** [comment]
old-mode-line-theme
updated-mode-line-theme

@nashamri I've attached them to this comment.

**Comment by nashamri** [comment]
Yeah thanks! that look more readable :+1:

**Comment by nashamri** [comment]
> I don't actually use spacemacs, just the theme, so my mode-line looks slightly different. But the colors are the same.

Spacemacs is a gateway drug to emacs :smile: were you using it before?

**Comment by jabranham** [comment]
> Spacemacs is a gateway drug to emacs smile were you using it before?

Nope, just enjoy the theme :-)

**Comment by nashamri** [comment]
Glad to hear that! 
Thanks @jabranham :smile:

**Pull request merged**
