### PR TITLE
Themed centaur-tabs and doom-modeline's bar

### PR DESCRIPTION
**Pull request by ema2159**
Hi! I themed my package (centaur-tabs, try it out!) and doom-modeline. Check it out:

DeepinScreenshot_select-area_20190704090258

### CODE REVIEW

**Comment by nashamri** [comment]
Hello @ema2159 thanks for this. Just a small note for your next PR :smile:, can you please make sure to squash the commits into one commit? This PR has two commits the first one is just to sync with `master`.

**Comment by ema2159** [comment]
Hi @nashamri! Is it still necessary? You could do also squash an merge, I think it's the same.

**Comment by nashamri** [comment]
Hey, yeah I did squash and merge this PR, I'm talking about your **next** PR :smile:

**Comment by ema2159** [comment]
Ah, now I get it jaja. I usually don't do this mistakes jaja, next time it won't happen!

**Pull request merged**
