### PR TITLE
Make deadlines in org agenda bold, and advance green-->orange-->red

### PR DESCRIPTION
**Pull request by jabranham**

### CODE REVIEW

**Comment by jabranham** [comment]
org-upcoming-distant-deadline won't exist until the next minor release (9.2), but after that this commit means that deadlines in the agenda will be bold for visual distinction from scheduled tasks, and advance from green to orange to red based on the distance to the deadline date and warning time.

**Comment by nashamri** [comment]
Thanks @jabranham :+1:

**Comment by jabranham** [comment]
BTW is there a way to re-apply the setup in spacetheme-common.el without needing to restart emacs? Usually with .el files, you can do `eval-buffer`, but that doesn't seem to work here.

**Comment by nashamri** [comment]
I usually do `, e b` which is bound to `eval-buffer` I think, and then I do `SPC T s` which calls `(spacemacs/helm-themes)` and pick the theme from there.

**Comment by jabranham** [comment]
Ahhh, you have to re-apply the theme. That makes sense, thanks!

**Pull request merged**
