### PR TITLE
Make cursor more visible

### PR DESCRIPTION
**Pull request by sooheon**
I made a PR on the spacemacs repo as well, before I knew this existed. I think light on dark and vice versa will be more visible for the cursors. Love the theme, btw.

### CODE REVIEW

**Comment by nashamri** [comment]
Hey, thanks for the PR :smile:. I think it's best to send PRs here as our workflow now is develop the theme incrementally here. And once we have good progress, we send a PR for the official spacemacs repo to be merged. Because I don't want to have conflicts with the one in the official repo.
Eventually, this will be sent to MELPA and everybody can easily get the complete theme.

**Comment by sooheon** [comment]
Ok will go ahead and close the spacemacs one.

**Comment by nashamri** [comment]
Much appreciated! :+1:

**Comment by sooheon** [comment]
Hey just a reminder, if there's not anything you're planning to tweak for this theme soon, could you PR to  spacemacs or put it up on melpa? ;)

**Comment by nashamri** [comment]
Hey! no it's not done yet :) I'm on vacation and once I get back home, I'll
start working on it again.

**Comment by sooheon** [comment]
Ok :)

**Comment by nashamri** [comment]
It just got added to melpa :)

**Pull request merged**
